#!/usr/bin/env python3
"""
Pod Consistency Verification Test

Verifies the critical pod consistency requirement:
When 4 teams are matched together in a round, ALL 4 players from each team
must face each other across exactly 4 separate pods. No mixing with other teams.

Example for teams A, B, C, D matched together:
  Pod 1: Team A Player 1, Team B Player 1, Team C Player 1, Team D Player 1
  Pod 2: Team A Player 2, Team B Player 2, Team C Player 2, Team D Player 2
  Pod 3: Team A Player 3, Team B Player 3, Team C Player 3, Team D Player 3
  Pod 4: Team A Player 4, Team B Player 4, Team C Player 4, Team D Player 4

Requirements Verified:
1. Pod Consistency: Teams matched together stay together across all 4 pods
2. No Teammate Violations: Players never face their own teammates
3. Player-level Repeat Avoidance: When teams meet again, different players face each other
4. Complete Player Participation: All players appear exactly once per round
"""

import sys
import os
from collections import defaultdict

# Set UTF-8 encoding
if sys.platform == 'win32':
    import codecs
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')
    os.environ['PYTHONIOENCODING'] = 'utf-8'

from tournament_dashboard import TournamentManager

class Colors:
    GREEN = '\033[92m'
    RED = '\033[91m'
    YELLOW = '\033[93m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    BOLD = '\033[1m'
    END = '\033[0m'

def print_header(text):
    print(f"\n{Colors.BOLD}{Colors.CYAN}{'='*80}{Colors.END}")
    print(f"{Colors.BOLD}{Colors.CYAN}{text.center(80)}{Colors.END}")
    print(f"{Colors.BOLD}{Colors.CYAN}{'='*80}{Colors.END}\n")

def print_success(text):
    print(f"{Colors.GREEN}✓ {text}{Colors.END}")

def print_error(text):
    print(f"{Colors.RED}✗ {text}{Colors.END}")

def print_warning(text):
    print(f"{Colors.YELLOW}⚠ {text}{Colors.END}")

def simulate_round_results(t, round_num):
    """Simulate results for a round by assigning random winners."""
    import random
    if round_num not in t.tables:
        return

    for table_id, table_data in t.tables[round_num].items():
        players = table_data.get('players', []) if isinstance(table_data, dict) else table_data
        if not players:
            continue

        # Pick a random winner
        winner = random.choice(players)
        winner_id = winner['Player ID']

        # Submit results
        for player in players:
            player_id = player['Player ID']
            if player_id == winner_id:
                t.player_scores[player_id] = t.player_scores.get(player_id, 0) + 5
            # Losers get 0 points

        # Update team scores
        for player in players:
            team_name = player['Team Name']
            t.scores[team_name] = sum(
                t.player_scores.get(p['Player ID'], 0)
                for p in t.teams[team_name]
            )

def verify_pod_consistency(team_count):
    """Verify all pod consistency requirements"""
    print_header(f"Pod Consistency Verification - {team_count} Teams")

    # Initialize tournament
    t = TournamentManager()
    t.create_sample_data(num_teams=team_count)
    t.setup_tournament()

    # Build mappings
    team_players = {}
    player_team = {}
    for team, players in t.teams.items():
        team_players[team] = [p['Player Name'] for p in players]
        for p in players:
            player_team[p['Player Name']] = team

    all_violations = []
    all_warnings = []

    # Track player matchup history for repeat detection
    player_matchup_history = defaultdict(set)  # player -> set of opponents faced

    # Check each round - generate incrementally with simulated results
    for round_num in range(1, t.swiss_rounds_count + 1):
        print(f"\n{Colors.BOLD}Round {round_num}:{Colors.END}")

        # Generate next round if not round 1 (round 1 is generated by setup_tournament)
        if round_num > 1:
            simulate_round_results(t, round_num - 1)
            t.generate_swiss_round(round_num)

        if round_num not in t.tables:
            print_error(f"Round {round_num} not generated!")
            all_violations.append(f"Round {round_num} not generated")
            continue

        tables = t.tables[round_num]

        # Group tables by team sets
        team_matchups = defaultdict(list)

        for table_id, table_data in tables.items():
            players = table_data.get('players', []) if isinstance(table_data, dict) else table_data

            # Use embedded Team Name from player dict, NOT name lookup (handles duplicate names)
            teams_at_table = sorted(set([p['Team Name'] for p in players]))
            team_key = tuple(teams_at_table)
            team_matchups[team_key].append((table_id, players))

        # Verify each team matchup group
        for team_set, table_list in sorted(team_matchups.items()):
            print(f"\n  Team Matchup: {', '.join(team_set)}")

            # Check 1: Must have exactly 4 tables
            if len(table_list) != 4:
                error = f"Round {round_num}: {team_set} - Expected 4 pods, got {len(table_list)}"
                all_violations.append(error)
                print_error(f"    {error}")
            else:
                print_success(f"    4 pods created (one per player)")

            # Check 2: Each team must have exactly 1 player per pod
            for table_id, players_in_pod in table_list:
                # Use embedded Team Name from player dict
                teams_in_pod = [p['Team Name'] for p in players_in_pod]
                team_counts = {}
                for team in teams_in_pod:
                    team_counts[team] = team_counts.get(team, 0) + 1

                for team, count in team_counts.items():
                    if count != 1:
                        error = f"Round {round_num}, {table_id}: {team} has {count} players (should be 1)"
                        all_violations.append(error)
                        print_error(f"    {error}")

            # Check 3: All 4 players from each team must participate
            teams_in_group = set(team_set)
            player_participation = defaultdict(set)  # team -> set of player names who played

            for table_id, players_in_pod in table_list:
                for p in players_in_pod:
                    # Use embedded Team Name from player dict
                    team = p['Team Name']
                    player_participation[team].add(p['Player Name'])

            for team in teams_in_group:
                expected_players = set(team_players[team])
                actual_players = player_participation[team]

                if expected_players != actual_players:
                    missing = expected_players - actual_players
                    extra = actual_players - expected_players
                    error = f"Round {round_num}: {team} - Missing: {missing}, Extra: {extra}"
                    all_violations.append(error)
                    print_error(f"    {error}")
                else:
                    print_success(f"    All 4 players from {team} participated")

        # Check 4: Track player matchups for repeats (using Player ID to handle duplicate names)
        for table_id, table_data in tables.items():
            players = table_data.get('players', []) if isinstance(table_data, dict) else table_data
            player_ids = [p['Player ID'] if isinstance(p, dict) else p for p in players]
            player_names = {p['Player ID']: p['Player Name'] for p in players if isinstance(p, dict)}

            for pid in player_ids:
                opponents = [opp for opp in player_ids if opp != pid]
                for opp in opponents:
                    # Check if already faced
                    if opp in player_matchup_history[pid]:
                        pname = player_names.get(pid, str(pid))
                        opp_name = player_names.get(opp, str(opp))
                        warning = f"Round {round_num}: {pname} (ID:{pid}) faces {opp_name} (ID:{opp}) again (repeat matchup)"
                        all_warnings.append(warning)

                    # Record matchup
                    player_matchup_history[pid].add(opp)

    # Summary
    print_header("Verification Summary")

    print(f"Total Teams: {team_count}")
    print(f"Total Players: {team_count * 4}")
    print(f"Swiss Rounds: {t.swiss_rounds_count}")
    print()

    if not all_violations:
        print_success(f"{Colors.BOLD}ALL POD CONSISTENCY CHECKS PASSED!{Colors.END}")
    else:
        print_error(f"{Colors.BOLD}Found {len(all_violations)} violations:{Colors.END}")
        for v in all_violations[:10]:
            print(f"  - {v}")

    print()

    if all_warnings:
        print_warning(f"Found {len(all_warnings)} player-level repeat matchups:")
        for w in all_warnings[:10]:
            print(f"  - {w}")
        if team_count in [8, 12]:
            print_warning("(Acceptable for 8 and 12 team tournaments)")
    else:
        print_success("Zero player-level repeat matchups")

    return len(all_violations) == 0

def main():
    """Run pod consistency verification for all tournament sizes"""
    print_header("MTG Tournament - Pod Consistency Verification")

    results = {}
    for team_count in [8, 12, 16]:
        success = verify_pod_consistency(team_count)
        results[team_count] = success

    # Final summary
    print_header("Overall Results")

    all_passed = all(results.values())

    for tc, success in results.items():
        status = f"{Colors.GREEN}PASS{Colors.END}" if success else f"{Colors.RED}FAIL{Colors.END}"
        print(f"{tc} teams: {status}")

    print()
    if all_passed:
        print_success(f"{Colors.BOLD}ALL TOURNAMENTS PASSED POD CONSISTENCY VERIFICATION!{Colors.END}")
        return 0
    else:
        print_error(f"{Colors.BOLD}SOME TOURNAMENTS FAILED VERIFICATION{Colors.END}")
        return 1

if __name__ == "__main__":
    sys.exit(main())
